In [19]:
import numpy as np

# Objective Function (Sphere)
def objective_function(x):
    return np.sum(x**2)

# Grey Wolf Optimizer
def grey_wolf_optimization(func, dim, wolves_count, iterations, bounds):
    wolves = np.random.uniform(bounds[0], bounds[1], (wolves_count, dim))
    alpha = beta = delta = np.zeros(dim)
    a_score = b_score = d_score = float('inf')

    print("Initial Wolves' Positions:\n", wolves)

    for t in range(iterations):
        for i in range(wolves_count):
            fitness = func(wolves[i])

            if fitness < a_score:
                d_score, delta = b_score, beta.copy()
                b_score, beta = a_score, alpha.copy()
                a_score, alpha = fitness, wolves[i].copy()
            elif fitness < b_score:
                d_score, delta = b_score, beta.copy()
                b_score, beta = fitness, wolves[i].copy()
            elif fitness < d_score:
                d_score, delta = fitness, wolves[i].copy()

        a = 2 - t * (2 / iterations)  # Decrease linearly

        for i in range(wolves_count):
            for j in range(dim):
                def update_position(leader):
                    r1, r2 = np.random.rand(), np.random.rand()
                    A = 2 * a * r1 - a
                    C = 2 * r2
                    D = abs(C * leader[j] - wolves[i][j])
                    return leader[j] - A * D

                X1 = update_position(alpha)
                X2 = update_position(beta)
                X3 = update_position(delta)

                wolves[i][j] = (X1 + X2 + X3) / 3

        print(f"\nIteration {t+1}/{iterations}: Best Fitness = {a_score:.5f}")

    print("\nOptimization Complete!")
    print("Best Position Found (Alpha Wolf):", alpha)
    print("Best Fitness Value:", a_score)

# Parameters
dim = 5
wolves = 10
iters = 20
bounds = (-10, 10)

# Run GWO
grey_wolf_optimization(objective_function, dim, wolves, iters, bounds)


Initial Wolves' Positions:
 [[-6.34970929 -2.20293845 -4.59690513  6.27748389  7.21582273]
 [ 0.12820566  5.7081598  -1.12012205  6.32558422  9.77542377]
 [-8.83985875  8.45802938 -5.77900018 -2.98970146  2.1489124 ]
 [ 2.14588625 -9.95197516 -3.4745808   5.98713575  8.69027572]
 [ 1.48757532  0.87387574  5.54603465 -3.54256034  6.21943917]
 [ 8.26715332  8.03434067  8.97638217 -2.79424069  5.82195013]
 [-9.25140501  4.54237522  4.28768984  2.62231667  8.13737687]
 [ 7.40022986  4.34010498 -0.39241406 -1.47188244  3.86995582]
 [-5.14943349 -6.92726011  4.07446407 -7.90637462  4.15415851]
 [-8.5563176  -3.55428895  2.36572725 -7.94185689  9.4176173 ]]

Iteration 1/20: Best Fitness = 84.96620

Iteration 2/20: Best Fitness = 45.76165

Iteration 3/20: Best Fitness = 35.47815

Iteration 4/20: Best Fitness = 28.13443

Iteration 5/20: Best Fitness = 16.90489

Iteration 6/20: Best Fitness = 5.77859

Iteration 7/20: Best Fitness = 2.12383

Iteration 8/20: Best Fitness = 0.86480

Iteration 9/20: